builders:
  asset_builder:
    import: "package:asset_flow/builder.dart"
    builder_factories: ["assetBuilder"]
    build_extensions: { ".txt": [".dart"] }
    build_to: source
    auto_apply: root_package
