builders:
  asset_builder:
    import: "package:asset_flow/builder.dart"
    builder_factories: ["assetBuilder"]
    build_extensions:
      { "$package$": ["lib/src/resources/assets/asset_flow.dart"] }
    auto_apply: dependents
    build_to: source
