name: asset_flow
description: Flutter code generator for your assets.
version: 0.0.1
homepage: https://github.com/DavidNovak1521/asset_flow
repository: https://github.com/DavidNovak1521/asset_flow
documentation: https://github.com/DavidNovak1521/asset_flow

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  build: ^2.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
