name: asset_flow
description: A Flutter code generator that simplifies asset management by automating the generation of asset-related code, making it easier to use resources like images and animations.
version: 0.0.4
homepage: https://github.com/DavidNovak1521/asset_flow
repository: https://github.com/DavidNovak1521/asset_flow
documentation: https://github.com/DavidNovak1521/asset_flow

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  build: ^2.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
